---
- name: "Installing Docker and Prerequisite Centos packages"
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
    state: latest
    update_cache: true
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  notify: "Start and Enable Docker Service"
  tags:
    - ce

- name: "Installing Docker and Prerequisite ubuntu packages"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify: "Start and Enable Docker Service"
  tags:
    - ce
