---
# handlers file for docker
#
- name: "Start and Enable Docker Service"
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - always

- name: "Restart Docker Service"
  service:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags:
    - always

- name: "set service to automatic"
  win_shell: Set-Service -Name docker -StartupType ‘Automatic’
  tags:
    - always

- name: "Reboot the machine with all defaults"
  win_reboot:
  tags:
    - always
