---
# handlers file for docker
#
- name: "Start and Enable Docker Service"
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - always

- name: "Restart Docker Service"
  service:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags:
    - always
